#!/usr/bin/env bash
# Assert that an exported .ipa is the build we meant to ship.
#
#   ios/scripts/assert-ipa.sh build/export-353/Apex-353.ipa
#
# Four things no export had ever been checked for (G11, issue #208):
#
#   1. No Fixtures/. ios/project.yml bundles ios/Fixtures as a folder-reference
#      resource for the -apexMockClient seam, and EXCLUDED_SOURCE_FILE_NAMES in
#      Config/Release.xcconfig is the only thing keeping 180 KB of test JSON out
#      of a shipped build. Nothing fails if that line is edited away.
#   2. The baked-in anon key is this project's. Config/Secrets.xcconfig is
#      git-ignored and regenerated by scraping the deployed web bundle, so
#      whatever that scrape found is what lands in Info.plist.
#   3. The baked-in origins are production. Info.plist takes APEX_API_BASE and
#      SUPABASE_URL from the xcconfig through $(...) substitution (D-022); a
#      Local export points the shipped app at 127.0.0.1.
#   4. It was built Release — which is what (1) and (3) depend on.
#
# Every failure is reported, then the script exits 1, so one run tells you
# everything that is wrong with the archive.
#
# Runs on a Mac (plutil, for the binary plist a real export produces) and on
# Linux (python3 plistlib, for a hand-built .ipa in a test).
set -euo pipefail

IPA="${1:-}"
[ -n "$IPA" ] || { echo "usage: ios/scripts/assert-ipa.sh <path.ipa>" >&2; exit 64; }
[ -f "$IPA" ] || { echo "error: no such file: $IPA" >&2; exit 1; }

# What Config/Release.xcconfig bakes in. Overridable only so the assertions
# themselves can be exercised against a deliberately wrong bundle.
PROJECT_REF="${APEX_PROJECT_REF:-prmlzrkcfvmfapauoxqn}"
EXPECTED_API_BASE="${APEX_EXPECTED_API_BASE:-https://apex-training.app}"
EXPECTED_SUPABASE_URL="${APEX_EXPECTED_SUPABASE_URL:-https://$PROJECT_REF.supabase.co}"
EXPECTED_CONFIGURATION="${APEX_EXPECTED_CONFIGURATION:-Release}"

command -v unzip >/dev/null 2>&1 || { echo "error: need unzip" >&2; exit 1; }
if ! command -v plutil >/dev/null 2>&1 && ! command -v python3 >/dev/null 2>&1; then
  echo "error: need plutil (macOS) or python3 to read Info.plist" >&2
  exit 1
fi

failures=0
ok()   { echo "   ✓ $*"; }
fail() { echo "   ✗ $*" >&2; failures=$((failures + 1)); }

# ── Info.plist ──────────────────────────────────────────────────────────────
listing=$(unzip -Z1 "$IPA")

plist_entry=$(printf '%s\n' "$listing" | grep -E '^Payload/[^/]+\.app/Info\.plist$' || true)
if [ -z "$plist_entry" ] || [ "$(printf '%s\n' "$plist_entry" | wc -l | tr -d ' ')" != 1 ]; then
  echo "error: expected exactly one Payload/<name>.app/Info.plist in $IPA, found: ${plist_entry:-none}" >&2
  exit 1
fi

WORK=$(mktemp -d)
trap 'rm -rf "$WORK"' EXIT
unzip -p "$IPA" "$plist_entry" > "$WORK/Info.plist"

# A real export writes a binary plist; plutil reads both, plistlib reads both.
plist_value() {
  if command -v plutil >/dev/null 2>&1; then
    plutil -extract "$1" raw -o - "$WORK/Info.plist" 2>/dev/null
  else
    python3 - "$WORK/Info.plist" "$1" <<'PY'
import plistlib, sys
with open(sys.argv[1], "rb") as handle:
    plist = plistlib.load(handle)
value = plist.get(sys.argv[2])
if not isinstance(value, str):
    sys.exit(1)
print(value)
PY
  fi
}

# ── JWT claims ──────────────────────────────────────────────────────────────
# Decoding a JWT payload needs base64url, which neither macOS's nor GNU's
# base64 does; both platforms have one of these two. (The same decoder as
# ios/scripts/secrets.sh — duplicated rather than sourced, because that script
# does its work at the top level and sourcing it would run it.)
if command -v python3 >/dev/null 2>&1; then
  JWT_DECODER=python3
elif command -v node >/dev/null 2>&1; then
  JWT_DECODER=node
else
  echo "error: need python3 or node to validate the anon key" >&2
  exit 1
fi

# Echo "<role> <ref> <exp>" from a JWT's payload; non-zero if it is not a
# three-part token with a decodable JSON object payload. Missing claims come
# back as "-" so the field count never shifts.
jwt_claims() {
  case $JWT_DECODER in
    python3)
      printf '%s' "$1" | python3 -c '
import base64, json, sys
parts = sys.stdin.read().strip().split(".")
if len(parts) != 3:
    sys.exit(1)
try:
    pad = "=" * (-len(parts[1]) % 4)
    payload = json.loads(base64.urlsafe_b64decode(parts[1] + pad))
except Exception:
    sys.exit(1)
if not isinstance(payload, dict):
    sys.exit(1)
print(*[str(payload.get(k, "-") or "-") for k in ("role", "ref", "exp")])
' ;;
    node)
      printf '%s' "$1" | node -e '
let raw = "";
process.stdin.on("data", (c) => (raw += c)).on("end", () => {
  const parts = raw.trim().split(".");
  if (parts.length !== 3) process.exit(1);
  let payload;
  try {
    payload = JSON.parse(Buffer.from(parts[1], "base64url").toString("utf8"));
  } catch {
    process.exit(1);
  }
  if (typeof payload !== "object" || payload === null) process.exit(1);
  console.log(["role", "ref", "exp"].map((k) => String(payload[k] ?? "-") || "-").join(" "));
});
' ;;
  esac
}

# Echo a one-line reason and return 1 unless the key is this project's
# unexpired anon key; echo its claims and return 0 when it is.
check_key() {
  local key=$1 claims role ref exp now
  claims=$(jwt_claims "$key") || { echo "not a decodable JWT"; return 1; }
  read -r role ref exp <<<"$claims"
  [ "$role" = anon ] || { echo "role is \"$role\", expected \"anon\""; return 1; }
  [ "$ref" = "$PROJECT_REF" ] || { echo "ref is \"$ref\", expected \"$PROJECT_REF\""; return 1; }
  case $exp in
    '' | *[!0-9]*) echo "exp is \"$exp\", expected a Unix timestamp"; return 1 ;;
  esac
  now=$(date -u +%s)
  [ "$exp" -gt "$now" ] || { echo "expired $(( (now - exp) / 86400 )) days ago (exp $exp)"; return 1; }
  echo "role anon, ref $ref, exp $exp"
}

# ── the assertions ──────────────────────────────────────────────────────────
echo "── asserting $IPA"

fixtures=$(printf '%s\n' "$listing" | grep -E '(^|/)Fixtures(/|$)' || true)
if [ -n "$fixtures" ]; then
  count=$(printf '%s\n' "$fixtures" | wc -l | tr -d ' ')
  fail "$count Fixtures entries in the bundle (EXCLUDED_SOURCE_FILE_NAMES in Config/Release.xcconfig):"
  printf '%s\n' "$fixtures" | head -5 | sed 's/^/       /' >&2
  if [ "$count" -gt 5 ]; then echo "       … and $((count - 5)) more" >&2; fi
else
  ok "no Fixtures/ entries"
fi

key=$(plist_value SUPABASE_ANON_KEY || true)
if [ -z "$key" ]; then
  fail "SUPABASE_ANON_KEY is missing or empty (did \$(SUPABASE_ANON_KEY) substitute?)"
elif detail=$(check_key "$key"); then
  ok "SUPABASE_ANON_KEY: $detail"
else
  fail "SUPABASE_ANON_KEY: $detail"
fi

expect_plist() { # <key> <expected>
  local actual
  actual=$(plist_value "$1" || true)
  if [ "$actual" = "$2" ]; then
    ok "$1 = $2"
  else
    fail "$1 is \"$actual\", expected \"$2\""
  fi
}

expect_plist APEX_API_BASE "$EXPECTED_API_BASE"
expect_plist SUPABASE_URL "$EXPECTED_SUPABASE_URL"
expect_plist APEX_CONFIGURATION "$EXPECTED_CONFIGURATION"

if [ "$failures" -gt 0 ]; then
  echo "error: $(basename "$IPA") failed $failures assertion(s) — do not ship it" >&2
  exit 1
fi
echo "── ok: $(basename "$IPA") is a production Release export"
