#!/usr/bin/env -S npx tsx
// Renders the connector guide's eight annotated illustrations
// (src/components/profile/ConnectorFigures.tsx) into ApexUI's asset catalog as
// PNGs, and emits the Swift catalog of their titles, callout pins and notes.
//
// The figures are React SVG components, so the path is: React → static SVG
// markup → Chromium (the repo's Playwright, as render-icon.mjs does) → PNG at
// 2x and 3x. The screen renders them at 2:1.25 (640×400 points), so the sizes
// are 1280×800 and 1920×1200. The house fonts are inlined from ApexUI's own
// TTFs so the drawings match the ones on the web rather than falling back to
// whatever the Mac has installed.
//
//   npx tsx --tsconfig tsconfig.app.json ios/scripts/gen-connector-figures.ts           # write
//   npx tsx --tsconfig tsconfig.app.json ios/scripts/gen-connector-figures.ts --check   # the Swift side + that every PNG exists (bytes vary by Chromium build)
// (`--tsconfig tsconfig.app.json` is what turns on the automatic JSX runtime; the root tsconfig only references it.)
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createElement } from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
import * as figures from '../../src/components/profile/ConnectorFigures';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..', '..');
const UI = join(ROOT, 'ios/Packages/ApexKit/Sources/ApexUI');
const CATALOG = join(UI, 'Resources/ConnectorFigures.xcassets');
const SWIFT = join(UI, 'Generated/ConnectorFigures.swift');
const FONTS = join(UI, 'Resources/Fonts');
const check = process.argv.includes('--check');

// The guide walks through them in this order; the ids are the asset names.
const SPECS: figures.FigureSpec[] = [
  figures.CLAUDE_CONNECTORS, figures.CLAUDE_ADD_DIALOG, figures.APEX_CONSENT, figures.CLAUDE_CHAT,
  figures.GPT_DEVELOPER_MODE, figures.GPT_CREATE, figures.GPT_CHAT, figures.APEX_TOKEN,
];

const swiftString = (s: string) => `"${s.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`;
const swiftIdent = (id: string) => id.replace(/-([a-z])/g, (_, c: string) => c.toUpperCase());

const swift = `// Generated by ios/scripts/gen-connector-figures.ts from src/components/profile/ConnectorFigures.tsx — do not edit.
import Foundation

/// The connector guide's illustrations: one entry per drawing in
/// ConnectorFigures.xcassets, with the callout text the web renders beneath
/// each. The image is \`figure-<id>\` at 640×400 points.
public enum ConnectorFigures {
    public struct Figure: Identifiable, Hashable, Sendable {
        public let id: String
        public let title: String
        /// Numbered callouts, matching the pins drawn on the figure.
        public let pins: [String]
        public let note: String?
        public var assetName: String { "figure-\\(id)" }
    }

${SPECS.map(spec => `    public static let ${swiftIdent(spec.id)} = Figure(
        id: ${swiftString(spec.id)},
        title: ${swiftString(spec.title)},
        pins: [
${spec.pins.map(pin => `            ${swiftString(pin)},`).join('\n')}
        ],
        note: ${spec.note ? swiftString(spec.note) : 'nil'}
    )`).join('\n\n')}

    public static let all: [Figure] = [${SPECS.map(s => swiftIdent(s.id)).join(', ')}]
}
`;

if (check) {
  if (!existsSync(SWIFT) || readFileSync(SWIFT, 'utf8') !== swift) {
    console.error(`::error::${SWIFT} is out of date — run npx tsx --tsconfig tsconfig.app.json ios/scripts/gen-connector-figures.ts`);
    process.exit(1);
  }
  for (const spec of SPECS) {
    if (!existsSync(join(CATALOG, `figure-${spec.id}.imageset`, `${spec.id}@2x.png`))) {
      console.error(`::error::missing figure ${spec.id} — run npx tsx --tsconfig tsconfig.app.json ios/scripts/gen-connector-figures.ts`);
      process.exit(1);
    }
  }
  process.exit(0);
}

const { chromium } = await import('playwright');
const font = (file: string) => `url(data:font/ttf;base64,${readFileSync(join(FONTS, file)).toString('base64')})`;
const css = `
  @font-face { font-family: Inter; font-weight: 400; src: ${font('Inter-Regular.ttf')}; }
  @font-face { font-family: Inter; font-weight: 500; src: ${font('Inter-Medium.ttf')}; }
  @font-face { font-family: Inter; font-weight: 600; src: ${font('Inter-SemiBold.ttf')}; }
  @font-face { font-family: Inter; font-weight: 700; src: ${font('Inter-Bold.ttf')}; }
  @font-face { font-family: 'JetBrains Mono'; font-weight: 400; src: ${font('JetBrainsMono-Regular.ttf')}; }
  @font-face { font-family: 'JetBrains Mono'; font-weight: 500; src: ${font('JetBrainsMono-Medium.ttf')}; }
  html, body { margin: 0; padding: 0; background: transparent; }
  svg { display: block; width: 640px; height: 400px; }
`;

mkdirSync(CATALOG, { recursive: true });
writeFileSync(join(CATALOG, 'Contents.json'), JSON.stringify({ info: { author: 'xcode', version: 1 } }, null, 2) + '\n');
const browser = await chromium.launch();
for (const spec of SPECS) {
  const markup = renderToStaticMarkup(
    createElement('svg', { xmlns: 'http://www.w3.org/2000/svg', viewBox: '0 0 640 400' }, createElement(spec.Svg)),
  );
  const set = join(CATALOG, `figure-${spec.id}.imageset`);
  mkdirSync(set, { recursive: true });
  for (const scale of [2, 3]) {
    const page = await browser.newPage({ viewport: { width: 640, height: 400 }, deviceScaleFactor: scale });
    await page.setContent(`<style>${css}</style>${markup}`);
    await page.evaluate(() => document.fonts.ready);
    await page.screenshot({ path: join(set, `${spec.id}@${scale}x.png`), omitBackground: true });
    await page.close();
  }
  writeFileSync(
    join(set, 'Contents.json'),
    JSON.stringify(
      {
        images: [
          { filename: `${spec.id}@2x.png`, idiom: 'universal', scale: '2x' },
          { filename: `${spec.id}@3x.png`, idiom: 'universal', scale: '3x' },
        ],
        info: { author: 'xcode', version: 1 },
      },
      null,
      2,
    ) + '\n',
  );
  console.log(`wrote figure-${spec.id}`);
}
await browser.close();
writeFileSync(SWIFT, swift);
console.log(`wrote ${SWIFT}`);
