#!/usr/bin/env node
// Emits the 24 profile avatars into ApexUI's asset catalog from the web's
// source of truth (`src/lib/profile/avatars.ts` + `src/assets/avatars/*.svg`),
// plus the Swift catalog of keys and labels — the same posture as
// gen-tokens.mjs: generated, never copied by hand, and `--check` fails on drift
// so the two clients can never disagree about which animals exist.
//
// The SVGs go into the catalog as SVGs: Xcode rasterises them at build time for
// every scale, and the drawings are plain paths and circles, which its renderer
// handles. The keys must stay in sync with the server's AVATAR_KEYS allowlist
// (api/_lib/handlers/profile.ts) — the web file is what that list is read from.
//
//   node ios/scripts/gen-avatars.mjs           # write
//   node ios/scripts/gen-avatars.mjs --check   # exit 1 on drift
import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..', '..');
const SOURCE = join(ROOT, 'src/lib/profile/avatars.ts');
const SVGS = join(ROOT, 'src/assets/avatars');
const CATALOG = join(ROOT, 'ios/Packages/ApexKit/Sources/ApexUI/Resources/Avatars.xcassets');
const SWIFT = join(ROOT, 'ios/Packages/ApexKit/Sources/ApexUI/Generated/Avatars.swift');
const check = process.argv.includes('--check');

// `'goat': { label: 'Mountain Goat', src: goatUrl },` — one line per avatar.
const entries = [...readFileSync(SOURCE, 'utf8').matchAll(/^\s*'([a-z-]+)':\s*\{\s*label:\s*'([^']+)'/gm)]
  .map(([, key, label]) => ({ key, label }));
if (entries.length !== 24) {
  console.error(`::error::expected 24 avatars in ${SOURCE}, parsed ${entries.length}`);
  process.exit(1);
}

const files = new Map();
files.set(join(CATALOG, 'Contents.json'), JSON.stringify({ info: { author: 'xcode', version: 1 } }, null, 2) + '\n');
for (const { key } of entries) {
  const svg = join(SVGS, `${key}.svg`);
  if (!existsSync(svg)) {
    console.error(`::error::missing ${svg}`);
    process.exit(1);
  }
  const set = join(CATALOG, `avatar-${key}.imageset`);
  files.set(join(set, `${key}.svg`), readFileSync(svg, 'utf8'));
  files.set(
    join(set, 'Contents.json'),
    JSON.stringify(
      {
        images: [{ filename: `${key}.svg`, idiom: 'universal' }],
        info: { author: 'xcode', version: 1 },
        properties: { 'preserves-vector-representation': true },
      },
      null,
      2,
    ) + '\n',
  );
}

const swift = `// Generated by ios/scripts/gen-avatars.mjs from src/lib/profile/avatars.ts — do not edit.
import SwiftUI

/// The twenty-four profile avatars, in the web's order. The keys are the
/// server's \`AVATAR_KEYS\` allowlist; the images live in Avatars.xcassets as
/// \`avatar-<key>\`.
public enum Avatars {
    public struct Avatar: Identifiable, Hashable, Sendable {
        public let key: String
        public let label: String
        public var id: String { key }
        /// The catalog name; \`AvatarImage\` is the view.
        public var assetName: String { "avatar-\\(key)" }
    }

    public static let all: [Avatar] = [
${entries.map(({ key, label }) => `        Avatar(key: "${key}", label: "${label}"),`).join('\n')}
    ]

    public static let defaultKey = "${entries[0].key}"

    public static func avatar(for key: String?) -> Avatar {
        all.first { $0.key == key } ?? all[0]
    }
}
`;
files.set(SWIFT, swift);

if (check) {
  let drift = false;
  const expectedSets = new Set(entries.map(({ key }) => `avatar-${key}.imageset`));
  for (const name of existsSync(CATALOG) ? readdirSync(CATALOG) : []) {
    if (name.endsWith('.imageset') && !expectedSets.has(name)) {
      console.error(`::error::stale ${join(CATALOG, name)} — run node ios/scripts/gen-avatars.mjs`);
      drift = true;
    }
  }
  for (const [path, content] of files) {
    if (!existsSync(path) || readFileSync(path, 'utf8') !== content) {
      console.error(`::error::${path} is out of date — run node ios/scripts/gen-avatars.mjs`);
      drift = true;
    }
  }
  process.exit(drift ? 1 : 0);
}

if (existsSync(CATALOG)) rmSync(CATALOG, { recursive: true });
for (const [path, content] of files) {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content);
}
console.log(`wrote ${entries.length} avatars to ${CATALOG} and ${SWIFT}`);
