#!/usr/bin/env bash
# Recreate ios/Config/Secrets.xcconfig in this worktree.
#
# WHY THIS EXISTS
# The file holds one value — the production Supabase anon key — and is
# git-ignored, so it lives in exactly one worktree and dies with it. Worktrees
# are removed by scripts/git-tidy.sh as soon as their PR merges, which has
# already silently taken this file twice. A device or Release build without it
# does not fail loudly at build time: it builds, installs, and then traps at
# launch on the REPLACE_ME sentinel.
#
# The key is public by construction — the web ships it in every page load, and
# RLS is what actually protects the data — so deriving it from the deployed
# bundle is not a credential leak. It is kept out of git only so the repo
# carries no production configuration at all.
#
#   ios/scripts/secrets.sh          write ios/Config/Secrets.xcconfig
#   ios/scripts/secrets.sh --check  exit 1 if it is missing or still a placeholder
#
# If the site is unreachable, take the key from Supabase → Project Settings → API.
set -euo pipefail
cd "$(cd "$(dirname "$0")/.." && pwd -P)"

OUT=Config/Secrets.xcconfig
ORIGIN="${APEX_PROD_URL:-https://apextrainingcalendar.vercel.app}"

if [ "${1:-}" = "--check" ]; then
  if [ ! -f "$OUT" ] || grep -q 'REPLACE_ME' "$OUT" || ! grep -q 'SUPABASE_ANON_KEY' "$OUT"; then
    echo "error: ios/$OUT is missing or unset — run ios/scripts/secrets.sh" >&2
    exit 1
  fi
  echo "ok: ios/$OUT is present"
  exit 0
fi

index=$(curl -fsSL "$ORIGIN/" 2>/dev/null) || {
  echo "error: could not reach $ORIGIN — take the anon key from Supabase → Settings → API" >&2
  exit 1
}
# The anon key is inlined in the built app bundle, which the browser downloads
# on every page load.
bundle_path=$(printf '%s' "$index" | grep -oE '/assets/index-[A-Za-z0-9._-]+\.js' | head -1)
[ -n "$bundle_path" ] || { echo "error: no app bundle found in $ORIGIN/" >&2; exit 1; }

key=$(curl -fsSL "$ORIGIN$bundle_path" \
  | grep -oE 'eyJ[A-Za-z0-9_-]+\.eyJ[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+|sb_publishable_[A-Za-z0-9_-]+' \
  | sort -u | head -1)
[ -n "$key" ] || { echo "error: no anon key found in $bundle_path" >&2; exit 1; }

mkdir -p Config
cat > "$OUT" <<CONF
// Git-ignored, and regenerated by ios/scripts/secrets.sh — do not commit.
// The anon key is public by construction (the web ships it in every page load);
// it lives outside git only so the repo carries no production configuration.
SUPABASE_ANON_KEY = $key
CONF
echo "wrote ios/$OUT (${#key}-character key from $bundle_path)"
