// GENERATED by scripts/db-types.sh from the local Supabase schema — do not edit.
// Regenerate after every migration (npm run db:types); CI's full job fails on drift.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      activity_streams: {
        Row: {
          activity_id: string
          created_at: string
          event_date: string
          event_id: string
          provider: string
          streams: Json | null
          summary: Json
          user_id: string
        }
        Insert: {
          activity_id: string
          created_at?: string
          event_date: string
          event_id: string
          provider: string
          streams?: Json | null
          summary: Json
          user_id: string
        }
        Update: {
          activity_id?: string
          created_at?: string
          event_date?: string
          event_id?: string
          provider?: string
          streams?: Json | null
          summary?: Json
          user_id?: string
        }
        Relationships: []
      }
      analytics_tiles: {
        Row: {
          created_at: string
          h: number
          id: string
          spec: Json
          updated_at: string
          user_id: string
          w: number
          x: number
          y: number
        }
        Insert: {
          created_at?: string
          h?: number
          id: string
          spec: Json
          updated_at?: string
          user_id: string
          w?: number
          x?: number
          y?: number
        }
        Update: {
          created_at?: string
          h?: number
          id?: string
          spec?: Json
          updated_at?: string
          user_id?: string
          w?: number
          x?: number
          y?: number
        }
        Relationships: []
      }
      api_request_counts: {
        Row: {
          bucket: string
          count: number
          user_id: string
          window_start: string
        }
        Insert: {
          bucket: string
          count?: number
          user_id: string
          window_start: string
        }
        Update: {
          bucket?: string
          count?: number
          user_id?: string
          window_start?: string
        }
        Relationships: []
      }
      block_mutations_log: {
        Row: {
          diff: Json | null
          id: string
          logged_at: string
          operation: string
          resource: string
          resource_id: string
          resource_name: string
          triggered_by: string
          user_id: string
        }
        Insert: {
          diff?: Json | null
          id?: string
          logged_at?: string
          operation: string
          resource: string
          resource_id: string
          resource_name: string
          triggered_by?: string
          user_id: string
        }
        Update: {
          diff?: Json | null
          id?: string
          logged_at?: string
          operation?: string
          resource?: string
          resource_id?: string
          resource_name?: string
          triggered_by?: string
          user_id?: string
        }
        Relationships: []
      }
      definition_mutations_log: {
        Row: {
          definition_id: string
          definition_name: string
          diff: Json | null
          id: string
          logged_at: string
          operation: string
          triggered_by: string
          user_id: string
        }
        Insert: {
          definition_id: string
          definition_name: string
          diff?: Json | null
          id?: string
          logged_at?: string
          operation: string
          triggered_by?: string
          user_id: string
        }
        Update: {
          definition_id?: string
          definition_name?: string
          diff?: Json | null
          id?: string
          logged_at?: string
          operation?: string
          triggered_by?: string
          user_id?: string
        }
        Relationships: []
      }
      event_mutations_log: {
        Row: {
          diff: Json | null
          event_date: string | null
          event_id: string
          event_title: string
          id: string
          logged_at: string
          operation: string
          triggered_by: string
          user_id: string
        }
        Insert: {
          diff?: Json | null
          event_date?: string | null
          event_id: string
          event_title: string
          id?: string
          logged_at?: string
          operation: string
          triggered_by?: string
          user_id: string
        }
        Update: {
          diff?: Json | null
          event_date?: string | null
          event_id?: string
          event_title?: string
          id?: string
          logged_at?: string
          operation?: string
          triggered_by?: string
          user_id?: string
        }
        Relationships: []
      }
      exercise_definitions: {
        Row: {
          aliases: string[]
          archived_at: string | null
          canonical_name: string
          category: string
          created_at: string
          default_duration: string | null
          default_reps: string | null
          default_rest: string | null
          default_sets: number | null
          default_weight: string | null
          equipment: string[]
          id: string
          image_url: string | null
          is_unilateral: boolean
          muscle_groups: string[]
          technique_notes: string | null
          updated_at: string
          user_id: string
        }
        Insert: {
          aliases?: string[]
          archived_at?: string | null
          canonical_name: string
          category: string
          created_at?: string
          default_duration?: string | null
          default_reps?: string | null
          default_rest?: string | null
          default_sets?: number | null
          default_weight?: string | null
          equipment?: string[]
          id: string
          image_url?: string | null
          is_unilateral?: boolean
          muscle_groups?: string[]
          technique_notes?: string | null
          updated_at?: string
          user_id: string
        }
        Update: {
          aliases?: string[]
          archived_at?: string | null
          canonical_name?: string
          category?: string
          created_at?: string
          default_duration?: string | null
          default_reps?: string | null
          default_rest?: string | null
          default_sets?: number | null
          default_weight?: string | null
          equipment?: string[]
          id?: string
          image_url?: string | null
          is_unilateral?: boolean
          muscle_groups?: string[]
          technique_notes?: string | null
          updated_at?: string
          user_id?: string
        }
        Relationships: []
      }
      mcp_tokens: {
        Row: {
          client_id: string | null
          created_at: string
          expires_at: string | null
          id: string
          kind: string
          last_used_at: string | null
          name: string
          revoked_at: string | null
          scope: string | null
          token_hash: string
          token_last4: string
          user_id: string
        }
        Insert: {
          client_id?: string | null
          created_at?: string
          expires_at?: string | null
          id?: string
          kind?: string
          last_used_at?: string | null
          name: string
          revoked_at?: string | null
          scope?: string | null
          token_hash: string
          token_last4: string
          user_id: string
        }
        Update: {
          client_id?: string | null
          created_at?: string
          expires_at?: string | null
          id?: string
          kind?: string
          last_used_at?: string | null
          name?: string
          revoked_at?: string | null
          scope?: string | null
          token_hash?: string
          token_last4?: string
          user_id?: string
        }
        Relationships: []
      }
      meal_favorites: {
        Row: {
          alcohol_g: number | null
          calories: number | null
          carbs_g: number | null
          created_at: string
          fat_saturated_g: number | null
          fat_total_g: number | null
          fat_trans_g: number | null
          fiber_g: number | null
          id: string
          meal_type: string | null
          notes: string
          protein_g: number | null
          sugar_g: number | null
          title: string
          updated_at: string
          user_id: string
        }
        Insert: {
          alcohol_g?: number | null
          calories?: number | null
          carbs_g?: number | null
          created_at?: string
          fat_saturated_g?: number | null
          fat_total_g?: number | null
          fat_trans_g?: number | null
          fiber_g?: number | null
          id: string
          meal_type?: string | null
          notes?: string
          protein_g?: number | null
          sugar_g?: number | null
          title: string
          updated_at?: string
          user_id: string
        }
        Update: {
          alcohol_g?: number | null
          calories?: number | null
          carbs_g?: number | null
          created_at?: string
          fat_saturated_g?: number | null
          fat_total_g?: number | null
          fat_trans_g?: number | null
          fiber_g?: number | null
          id?: string
          meal_type?: string | null
          notes?: string
          protein_g?: number | null
          sugar_g?: number | null
          title?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: []
      }
      meal_mutations_log: {
        Row: {
          diff: Json | null
          id: string
          logged_at: string
          meal_id: string
          meal_title: string
          operation: string
          triggered_by: string
          user_id: string
        }
        Insert: {
          diff?: Json | null
          id?: string
          logged_at?: string
          meal_id: string
          meal_title: string
          operation: string
          triggered_by?: string
          user_id: string
        }
        Update: {
          diff?: Json | null
          id?: string
          logged_at?: string
          meal_id?: string
          meal_title?: string
          operation?: string
          triggered_by?: string
          user_id?: string
        }
        Relationships: []
      }
      meals: {
        Row: {
          alcohol_g: number | null
          calories: number | null
          carbs_g: number | null
          created_at: string
          date: string
          fat_saturated_g: number | null
          fat_total_g: number | null
          fat_trans_g: number | null
          fiber_g: number | null
          id: string
          meal_type: string | null
          notes: string
          protein_g: number | null
          sugar_g: number | null
          time: string | null
          title: string
          updated_at: string
          user_id: string
        }
        Insert: {
          alcohol_g?: number | null
          calories?: number | null
          carbs_g?: number | null
          created_at?: string
          date: string
          fat_saturated_g?: number | null
          fat_total_g?: number | null
          fat_trans_g?: number | null
          fiber_g?: number | null
          id: string
          meal_type?: string | null
          notes?: string
          protein_g?: number | null
          sugar_g?: number | null
          time?: string | null
          title: string
          updated_at?: string
          user_id: string
        }
        Update: {
          alcohol_g?: number | null
          calories?: number | null
          carbs_g?: number | null
          created_at?: string
          date?: string
          fat_saturated_g?: number | null
          fat_total_g?: number | null
          fat_trans_g?: number | null
          fiber_g?: number | null
          id?: string
          meal_type?: string | null
          notes?: string
          protein_g?: number | null
          sugar_g?: number | null
          time?: string | null
          title?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: []
      }
      oauth_clients: {
        Row: {
          client_id: string
          client_name: string
          created_at: string
          redirect_uris: Json
        }
        Insert: {
          client_id: string
          client_name?: string
          created_at?: string
          redirect_uris: Json
        }
        Update: {
          client_id?: string
          client_name?: string
          created_at?: string
          redirect_uris?: Json
        }
        Relationships: []
      }
      oauth_codes: {
        Row: {
          client_id: string
          code_challenge: string
          code_hash: string
          consumed_at: string | null
          created_at: string
          expires_at: string
          redirect_uri: string
          resource: string | null
          scope: string | null
          user_id: string
        }
        Insert: {
          client_id: string
          code_challenge: string
          code_hash: string
          consumed_at?: string | null
          created_at?: string
          expires_at: string
          redirect_uri: string
          resource?: string | null
          scope?: string | null
          user_id: string
        }
        Update: {
          client_id?: string
          code_challenge?: string
          code_hash?: string
          consumed_at?: string | null
          created_at?: string
          expires_at?: string
          redirect_uri?: string
          resource?: string | null
          scope?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "oauth_codes_client_id_fkey"
            columns: ["client_id"]
            isOneToOne: false
            referencedRelation: "oauth_clients"
            referencedColumns: ["client_id"]
          },
        ]
      }
      objectives: {
        Row: {
          created_at: string
          discipline: string | null
          id: string
          name: string
          notes: string
          required_capabilities: Json
          status: string
          target_date: string | null
          updated_at: string
          user_id: string
        }
        Insert: {
          created_at?: string
          discipline?: string | null
          id?: string
          name: string
          notes?: string
          required_capabilities?: Json
          status?: string
          target_date?: string | null
          updated_at?: string
          user_id: string
        }
        Update: {
          created_at?: string
          discipline?: string | null
          id?: string
          name?: string
          notes?: string
          required_capabilities?: Json
          status?: string
          target_date?: string | null
          updated_at?: string
          user_id?: string
        }
        Relationships: []
      }
      phase32_quarantine: {
        Row: {
          event_id: string
          id: number
          quarantined_at: string
          row_data: Json
          stale_date: string
          table_name: string
          target_date: string
          user_id: string
        }
        Insert: {
          event_id: string
          id?: number
          quarantined_at?: string
          row_data: Json
          stale_date: string
          table_name: string
          target_date: string
          user_id: string
        }
        Update: {
          event_id?: string
          id?: number
          quarantined_at?: string
          row_data?: Json
          stale_date?: string
          table_name?: string
          target_date?: string
          user_id?: string
        }
        Relationships: []
      }
      profiles: {
        Row: {
          avatar_key: string
          coach_context: string
          coach_goal: string
          created_at: string
          display_name: string
          ics_token: string
          id: string
          is_template_source: boolean
          max_hr: number | null
          onboarding_dismissed_at: string | null
          template_copied_at: string | null
          threshold_hr: number | null
          updated_at: string
        }
        Insert: {
          avatar_key?: string
          coach_context?: string
          coach_goal?: string
          created_at?: string
          display_name?: string
          ics_token?: string
          id: string
          is_template_source?: boolean
          max_hr?: number | null
          onboarding_dismissed_at?: string | null
          template_copied_at?: string | null
          threshold_hr?: number | null
          updated_at?: string
        }
        Update: {
          avatar_key?: string
          coach_context?: string
          coach_goal?: string
          created_at?: string
          display_name?: string
          ics_token?: string
          id?: string
          is_template_source?: boolean
          max_hr?: number | null
          onboarding_dismissed_at?: string | null
          template_copied_at?: string | null
          threshold_hr?: number | null
          updated_at?: string
        }
        Relationships: []
      }
      provider_activity_imports: {
        Row: {
          activity_id: string
          event_date: string
          event_id: string
          imported_at: string
          mode: string
          provider: string
          user_id: string
        }
        Insert: {
          activity_id: string
          event_date: string
          event_id: string
          imported_at?: string
          mode: string
          provider: string
          user_id: string
        }
        Update: {
          activity_id?: string
          event_date?: string
          event_id?: string
          imported_at?: string
          mode?: string
          provider?: string
          user_id?: string
        }
        Relationships: []
      }
      provider_connections: {
        Row: {
          access_token: string | null
          auto_sync: boolean
          connected_at: string | null
          last_synced_at: string | null
          pending_fill_count: number
          pending_oauth: Json | null
          provider: string
          refresh_token: string | null
          status: string
          timezone: string | null
          token_expires_at: string | null
          updated_at: string
          user_id: string
        }
        Insert: {
          access_token?: string | null
          auto_sync?: boolean
          connected_at?: string | null
          last_synced_at?: string | null
          pending_fill_count?: number
          pending_oauth?: Json | null
          provider: string
          refresh_token?: string | null
          status?: string
          timezone?: string | null
          token_expires_at?: string | null
          updated_at?: string
          user_id: string
        }
        Update: {
          access_token?: string | null
          auto_sync?: boolean
          connected_at?: string | null
          last_synced_at?: string | null
          pending_fill_count?: number
          pending_oauth?: Json | null
          provider?: string
          refresh_token?: string | null
          status?: string
          timezone?: string | null
          token_expires_at?: string | null
          updated_at?: string
          user_id?: string
        }
        Relationships: []
      }
      recurring_exceptions: {
        Row: {
          created_at: string
          event_id: string
          id: string
          override_date: string | null
          override_end_time: string | null
          override_start_time: string | null
          skipped_date: string
          user_id: string
        }
        Insert: {
          created_at?: string
          event_id: string
          id?: string
          override_date?: string | null
          override_end_time?: string | null
          override_start_time?: string | null
          skipped_date: string
          user_id: string
        }
        Update: {
          created_at?: string
          event_id?: string
          id?: string
          override_date?: string | null
          override_end_time?: string | null
          override_start_time?: string | null
          skipped_date?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "recurring_exceptions_user_event_fkey"
            columns: ["user_id", "event_id"]
            isOneToOne: false
            referencedRelation: "workout_events"
            referencedColumns: ["user_id", "id"]
          },
        ]
      }
      reviews: {
        Row: {
          ai_commentary: string | null
          created_at: string
          email_sent_at: string | null
          email_skipped_reason: string | null
          id: string
          iso_year: number
          month_index: number | null
          period_type: string
          stats: Json
          updated_at: string
          user_id: string
        }
        Insert: {
          ai_commentary?: string | null
          created_at?: string
          email_sent_at?: string | null
          email_skipped_reason?: string | null
          id?: string
          iso_year: number
          month_index?: number | null
          period_type: string
          stats: Json
          updated_at?: string
          user_id: string
        }
        Update: {
          ai_commentary?: string | null
          created_at?: string
          email_sent_at?: string | null
          email_skipped_reason?: string | null
          id?: string
          iso_year?: number
          month_index?: number | null
          period_type?: string
          stats?: Json
          updated_at?: string
          user_id?: string
        }
        Relationships: []
      }
      training_blocks: {
        Row: {
          created_at: string
          end_date_exclusive: string
          id: string
          intent: string
          name: string
          objective_id: string | null
          phase: string | null
          start_date: string
          updated_at: string
          user_id: string
          weekly_targets: Json
        }
        Insert: {
          created_at?: string
          end_date_exclusive: string
          id?: string
          intent?: string
          name: string
          objective_id?: string | null
          phase?: string | null
          start_date: string
          updated_at?: string
          user_id: string
          weekly_targets?: Json
        }
        Update: {
          created_at?: string
          end_date_exclusive?: string
          id?: string
          intent?: string
          name?: string
          objective_id?: string | null
          phase?: string | null
          start_date?: string
          updated_at?: string
          user_id?: string
          weekly_targets?: Json
        }
        Relationships: [
          {
            foreignKeyName: "training_blocks_objective_id_fkey"
            columns: ["objective_id"]
            isOneToOne: false
            referencedRelation: "objectives"
            referencedColumns: ["id"]
          },
        ]
      }
      user_api_keys: {
        Row: {
          anthropic_api_key: string
          created_at: string
          updated_at: string
          user_id: string
        }
        Insert: {
          anthropic_api_key: string
          created_at?: string
          updated_at?: string
          user_id: string
        }
        Update: {
          anthropic_api_key?: string
          created_at?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: []
      }
      workout_cardio_logs: {
        Row: {
          avg_heart_rate: number | null
          definition_id: string | null
          distance: string | null
          duration_minutes: number | null
          elevation_gain: string | null
          event_date: string
          event_id: string
          exercise_id: string
          exercise_name: string
          id: string
          is_autofilled: boolean
          section: string
          updated_at: string
          user_id: string
        }
        Insert: {
          avg_heart_rate?: number | null
          definition_id?: string | null
          distance?: string | null
          duration_minutes?: number | null
          elevation_gain?: string | null
          event_date: string
          event_id: string
          exercise_id: string
          exercise_name: string
          id?: string
          is_autofilled?: boolean
          section: string
          updated_at?: string
          user_id: string
        }
        Update: {
          avg_heart_rate?: number | null
          definition_id?: string | null
          distance?: string | null
          duration_minutes?: number | null
          elevation_gain?: string | null
          event_date?: string
          event_id?: string
          exercise_id?: string
          exercise_name?: string
          id?: string
          is_autofilled?: boolean
          section?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: []
      }
      workout_completion_log: {
        Row: {
          action: string
          duration_minutes: number | null
          event_date: string
          event_id: string
          event_title: string
          event_type: string
          id: string
          logged_at: string
          user_id: string
        }
        Insert: {
          action: string
          duration_minutes?: number | null
          event_date: string
          event_id: string
          event_title: string
          event_type: string
          id?: string
          logged_at?: string
          user_id: string
        }
        Update: {
          action?: string
          duration_minutes?: number | null
          event_date?: string
          event_id?: string
          event_title?: string
          event_type?: string
          id?: string
          logged_at?: string
          user_id?: string
        }
        Relationships: []
      }
      workout_completions: {
        Row: {
          completed_at: string | null
          duration_minutes: number | null
          event_date: string
          event_id: string
          event_title: string
          event_type: string
          is_completed: boolean
          updated_at: string
          user_id: string
        }
        Insert: {
          completed_at?: string | null
          duration_minutes?: number | null
          event_date: string
          event_id: string
          event_title: string
          event_type: string
          is_completed?: boolean
          updated_at?: string
          user_id: string
        }
        Update: {
          completed_at?: string | null
          duration_minutes?: number | null
          event_date?: string
          event_id?: string
          event_title?: string
          event_type?: string
          is_completed?: boolean
          updated_at?: string
          user_id?: string
        }
        Relationships: []
      }
      workout_events: {
        Row: {
          cardio_targets: Json | null
          climbing_targets: Json | null
          cooldown: Json
          cover_image_url: string | null
          created_at: string
          date: string
          description: string
          difficulty: number
          end_time: string | null
          equipment: string[]
          estimated_duration: number
          exercises: Json
          id: string
          is_recurring: boolean
          location: string | null
          recurrence_rule: string | null
          recurring_days: number[] | null
          recurring_end_date: string | null
          recurring_frequency: string | null
          scoring_type: string | null
          source: string | null
          sport: string | null
          start_time: string | null
          subtitle: string | null
          tags: string[]
          template_id: string | null
          time_cap_minutes: number | null
          title: string
          type: string
          updated_at: string
          user_id: string
          warmup: Json
        }
        Insert: {
          cardio_targets?: Json | null
          climbing_targets?: Json | null
          cooldown?: Json
          cover_image_url?: string | null
          created_at?: string
          date: string
          description?: string
          difficulty: number
          end_time?: string | null
          equipment?: string[]
          estimated_duration: number
          exercises?: Json
          id: string
          is_recurring?: boolean
          location?: string | null
          recurrence_rule?: string | null
          recurring_days?: number[] | null
          recurring_end_date?: string | null
          recurring_frequency?: string | null
          scoring_type?: string | null
          source?: string | null
          sport?: string | null
          start_time?: string | null
          subtitle?: string | null
          tags?: string[]
          template_id?: string | null
          time_cap_minutes?: number | null
          title: string
          type: string
          updated_at?: string
          user_id: string
          warmup?: Json
        }
        Update: {
          cardio_targets?: Json | null
          climbing_targets?: Json | null
          cooldown?: Json
          cover_image_url?: string | null
          created_at?: string
          date?: string
          description?: string
          difficulty?: number
          end_time?: string | null
          equipment?: string[]
          estimated_duration?: number
          exercises?: Json
          id?: string
          is_recurring?: boolean
          location?: string | null
          recurrence_rule?: string | null
          recurring_days?: number[] | null
          recurring_end_date?: string | null
          recurring_frequency?: string | null
          scoring_type?: string | null
          source?: string | null
          sport?: string | null
          start_time?: string | null
          subtitle?: string | null
          tags?: string[]
          template_id?: string | null
          time_cap_minutes?: number | null
          title?: string
          type?: string
          updated_at?: string
          user_id?: string
          warmup?: Json
        }
        Relationships: []
      }
      workout_sessions: {
        Row: {
          coach_summary: string | null
          event_date: string
          event_id: string
          finished_at: string | null
          id: string
          score_reps: number | null
          score_rounds: number | null
          score_time_seconds: number | null
          score_type: string | null
          started_at: string
          template_id: string | null
          total_duration_seconds: number | null
          updated_at: string
          user_id: string
        }
        Insert: {
          coach_summary?: string | null
          event_date: string
          event_id: string
          finished_at?: string | null
          id?: string
          score_reps?: number | null
          score_rounds?: number | null
          score_time_seconds?: number | null
          score_type?: string | null
          started_at: string
          template_id?: string | null
          total_duration_seconds?: number | null
          updated_at?: string
          user_id: string
        }
        Update: {
          coach_summary?: string | null
          event_date?: string
          event_id?: string
          finished_at?: string | null
          id?: string
          score_reps?: number | null
          score_rounds?: number | null
          score_time_seconds?: number | null
          score_type?: string | null
          started_at?: string
          template_id?: string | null
          total_duration_seconds?: number | null
          updated_at?: string
          user_id?: string
        }
        Relationships: []
      }
      workout_set_logs: {
        Row: {
          actual_duration: string | null
          actual_reps: string | null
          actual_weight: string | null
          definition_id: string | null
          event_date: string
          event_id: string
          exercise_id: string
          exercise_name: string
          id: string
          is_autofilled: boolean
          planned_duration: string | null
          planned_reps: string | null
          planned_weight: string | null
          section: string
          set_number: number
          updated_at: string
          user_id: string
        }
        Insert: {
          actual_duration?: string | null
          actual_reps?: string | null
          actual_weight?: string | null
          definition_id?: string | null
          event_date: string
          event_id: string
          exercise_id: string
          exercise_name: string
          id?: string
          is_autofilled?: boolean
          planned_duration?: string | null
          planned_reps?: string | null
          planned_weight?: string | null
          section: string
          set_number: number
          updated_at?: string
          user_id: string
        }
        Update: {
          actual_duration?: string | null
          actual_reps?: string | null
          actual_weight?: string | null
          definition_id?: string | null
          event_date?: string
          event_id?: string
          exercise_id?: string
          exercise_name?: string
          id?: string
          is_autofilled?: boolean
          planned_duration?: string | null
          planned_reps?: string | null
          planned_weight?: string | null
          section?: string
          set_number?: number
          updated_at?: string
          user_id?: string
        }
        Relationships: []
      }
      workout_templates: {
        Row: {
          archived_at: string | null
          cardio_targets: Json | null
          climbing_targets: Json | null
          cooldown: Json
          created_at: string
          description: string
          difficulty: number
          equipment: string[]
          estimated_duration: number
          exercises: Json
          id: string
          location: string | null
          scoring_type: string
          sport: string | null
          tags: string[]
          time_cap_minutes: number | null
          title: string
          type: string
          updated_at: string
          user_id: string
          warmup: Json
        }
        Insert: {
          archived_at?: string | null
          cardio_targets?: Json | null
          climbing_targets?: Json | null
          cooldown?: Json
          created_at?: string
          description?: string
          difficulty?: number
          equipment?: string[]
          estimated_duration: number
          exercises?: Json
          id: string
          location?: string | null
          scoring_type?: string
          sport?: string | null
          tags?: string[]
          time_cap_minutes?: number | null
          title: string
          type: string
          updated_at?: string
          user_id: string
          warmup?: Json
        }
        Update: {
          archived_at?: string | null
          cardio_targets?: Json | null
          climbing_targets?: Json | null
          cooldown?: Json
          created_at?: string
          description?: string
          difficulty?: number
          equipment?: string[]
          estimated_duration?: number
          exercises?: Json
          id?: string
          location?: string | null
          scoring_type?: string
          sport?: string | null
          tags?: string[]
          time_cap_minutes?: number | null
          title?: string
          type?: string
          updated_at?: string
          user_id?: string
          warmup?: Json
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      bump_rate_limit: {
        Args: { p_bucket: string; p_user_id: string; p_window_seconds: number }
        Returns: number
      }
      last_performed_by_name: {
        Args: { p_user_id?: string }
        Returns: {
          event_date: string
          exercise_name: string
        }[]
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const

