import SwiftUI

/// One of the twenty-four avatars (Avatars.xcassets, generated by
/// `gen-avatars.mjs`), clipped to the circle the drawings already fill. An
/// unknown or missing key shows the first avatar, as the web's `avatarSrc` does.
public struct AvatarImage: View {
    private let avatar: Avatars.Avatar
    private let size: CGFloat

    public init(key: String?, size: CGFloat = 40) {
        self.avatar = Avatars.avatar(for: key)
        self.size = size
    }

    public var body: some View {
        Image(avatar.assetName, bundle: .module)
            .resizable()
            .interpolation(.high)
            .scaledToFit()
            .frame(width: size, height: size)
            .clipShape(.circle)
            .accessibilityLabel(avatar.label)
    }
}

/// `Bundle.module` for callers outside this module — the guide's figures and
/// the avatars are both ApexUI resources drawn by ApexFeatures.
public enum ApexUIBundle {
    public static let bundle = Bundle.module
}
