#!/usr/bin/env bash
# Regenerate src/lib/db/database.types.ts from the LOCAL Supabase stack, or
# prove the committed file still matches it.
#
#   scripts/db-types.sh            # regenerate (run after every migration)
#   scripts/db-types.sh --check    # exit 1 if the committed file is stale
#
# The generated file is what types both Supabase clients (src/lib/
# supabaseClient.ts, api/_lib/supabaseAdmin.ts) and what src/lib/db/types.ts
# derives the domain row types from, so a migration that changes a column
# without this being re-run leaves the code typed against a schema that no
# longer exists. CI's full job runs --check right after db-reset-local.sh,
# against a database built from scratch by every migration in the repo.
#
# LOCAL ONLY: --local talks to the running local stack's Postgres and nothing
# else. The CLI version is pinned because the generator's output format
# changes between releases, and a byte-for-byte drift check only means
# something against one version.
set -euo pipefail
cd "$(dirname "$0")/.."

OUT=src/lib/db/database.types.ts
# The iOS app's row types come from the same schema, same CLI, same run
# (docs/ios/architecture.md §13) — one migration regenerates both files.
OUT_SWIFT=ios/Packages/ApexCore/Sources/ApexCore/Generated/DatabaseTypes.swift
CLI_VERSION=2.115.0

generate() {
  printf '%s\n' \
    '// GENERATED by scripts/db-types.sh from the local Supabase schema — do not edit.' \
    "// Regenerate after every migration (npm run db:types); CI's full job fails on drift."
  npx --yes "supabase@$CLI_VERSION" gen types typescript --local --schema public
}

generate_swift() {
  printf '%s\n' \
    '// GENERATED by scripts/db-types.sh from the local Supabase schema — do not edit.' \
    "// Regenerate after every migration (npm run db:types); CI's full job fails on drift."
  npx --yes "supabase@$CLI_VERSION" gen types --lang swift --local --schema public
}

check_one() {
  local out=$1 gen=$2 tmp
  tmp=$(mktemp)
  "$gen" > "$tmp"
  if diff -u "$out" "$tmp"; then
    echo "ok: $out matches the local schema"
    rm -f "$tmp"
  else
    rm -f "$tmp"
    echo >&2
    echo "error: $out is stale — a migration changed the schema without regenerating the types." >&2
    echo "       Run 'npm run db:types' against a freshly reset local stack and commit the result." >&2
    exit 1
  fi
}

if [ "${1:-}" = "--check" ]; then
  check_one "$OUT" generate
  check_one "$OUT_SWIFT" generate_swift
else
  generate > "$OUT"
  echo "wrote $OUT"
  mkdir -p "$(dirname "$OUT_SWIFT")"
  generate_swift > "$OUT_SWIFT"
  echo "wrote $OUT_SWIFT"
fi
