-- ============================================================
-- APEX TRAINING — Phase 22 Migration: user-scoped workout_events PK
-- Run this in: Supabase Dashboard → SQL Editor → New query
--
-- Run BEFORE deploying the phase-22 code: api/event-instances.ts starts
-- upserting against the (user_id, event_id, skipped_date) constraint this
-- migration creates. (phase20 does not exist — the number was skipped;
-- phase21 is the previous migration.)
--
-- Finishes what phase9 §4 started. That migration re-keyed five tables to
-- user-prefixed primary keys — "a global PK would collide the moment a
-- second user adds an exercise Shane already has" — but left workout_events
-- as a GLOBAL `id TEXT PRIMARY KEY`. Consequences it fixes:
--   * user B inserting an id user A owns got a duplicate-key 500 — a
--     cross-user existence oracle and an id-squatting nuisance;
--   * recurring_exceptions still carried the global UNIQUE
--     (event_id, skipped_date), violating the "user_id leads every
--     conflict target" invariant (api/workout-sessions.ts).
-- ============================================================

DO $$
DECLARE cname text;
BEGIN
  -- Defensive: an exception row whose user_id disagrees with its event's
  -- owner would block the composite FK below. The API's ownership check
  -- has always prevented these; delete any stragglers as invalid data.
  DELETE FROM recurring_exceptions re
  USING workout_events we
  WHERE re.event_id = we.id AND re.user_id <> we.user_id;

  -- Drop the old single-column FK (autogenerated name — find it, never
  -- hardcode; same discipline as phase9).
  SELECT conname INTO cname FROM pg_constraint
   WHERE conrelid = 'recurring_exceptions'::regclass
     AND contype = 'f'
     AND confrelid = 'workout_events'::regclass;
  IF cname IS NOT NULL THEN
    EXECUTE format('ALTER TABLE recurring_exceptions DROP CONSTRAINT %I', cname);
  END IF;

  -- workout_events: PK id → (user_id, id)
  ALTER TABLE workout_events DROP CONSTRAINT workout_events_pkey;
  ALTER TABLE workout_events ADD PRIMARY KEY (user_id, id);

  -- Re-point the FK at the composite key, keeping the cascade.
  ALTER TABLE recurring_exceptions
    ADD CONSTRAINT recurring_exceptions_user_event_fkey
    FOREIGN KEY (user_id, event_id)
    REFERENCES workout_events (user_id, id)
    ON DELETE CASCADE;

  -- recurring_exceptions: UNIQUE (event_id, skipped_date) → user-prefixed.
  SELECT conname INTO cname FROM pg_constraint
   WHERE conrelid = 'recurring_exceptions'::regclass AND contype = 'u';
  EXECUTE format('ALTER TABLE recurring_exceptions DROP CONSTRAINT %I', cname);
  ALTER TABLE recurring_exceptions ADD UNIQUE (user_id, event_id, skipped_date);
END
$$;

-- ------------------------------------------------------------
-- Audit-log indexes. phase9 §5 added user_id indexes to the data tables
-- but skipped the append-only logs, which every AI-cap check filters by
-- (user_id, triggered_by, logged_at) and /api/mutations-log orders by
-- logged_at — seq scans that get slower forever without these.
-- ------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_eml_user_time  ON event_mutations_log (user_id, logged_at DESC);
CREATE INDEX IF NOT EXISTS idx_dml_user_time  ON definition_mutations_log (user_id, logged_at DESC);
CREATE INDEX IF NOT EXISTS idx_bml_user_time  ON block_mutations_log (user_id, logged_at DESC);
CREATE INDEX IF NOT EXISTS idx_wcl_user_time  ON workout_completion_log (user_id, logged_at DESC);
