-- ============================================================
-- APEX TRAINING — Phase 9 Migration: Multi-user foundation
-- Run this in: Supabase Dashboard → SQL Editor → New query
--
-- PREREQUISITE: create Shane's auth user (shanehaynes.sah@gmail.com) in
-- Dashboard → Authentication → Users BEFORE running this — the backfill
-- looks him up by email and aborts if he doesn't exist.
--
-- This migration is deliberately NON-BREAKING for the currently deployed
-- code: every table gains user_id with NOT NULL DEFAULT <shane's uid>, so
-- pre-auth writes from the old deploy keep landing as Shane. The defaults
-- and the anon read-all policies are dropped later in phase10, only after
-- the authenticated deploy is confirmed working.
-- ============================================================

-- ------------------------------------------------------------
-- 1) profiles — one row per auth user
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS profiles (
  id                 UUID        PRIMARY KEY REFERENCES auth.users (id) ON DELETE CASCADE,
  display_name       TEXT        NOT NULL DEFAULT '',
  avatar_key         TEXT        NOT NULL DEFAULT 'goat'
                     CHECK (avatar_key IN ('goat','ibex','snow-leopard','eagle','wolf')),
  -- The account whose recurring workouts seed new users' calendars.
  is_template_source BOOLEAN     NOT NULL DEFAULT false,
  -- Set exactly once by /api/template-copy; doubles as the idempotency lock.
  template_copied_at TIMESTAMPTZ,
  -- Capability token for the per-user ICS calendar feed (?token=).
  ics_token          UUID        NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;

-- Users read only their own profile; all writes go through service-role
-- /api/profile (which bypasses RLS), same posture as every other table.
CREATE POLICY user_select_own_profile
  ON profiles FOR SELECT
  TO authenticated
  USING (auth.uid() = id);

-- ------------------------------------------------------------
-- 2) Auto-create a profile whenever an auth user is created
--    (dashboard invite included), with a random animal avatar.
-- ------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
BEGIN
  INSERT INTO public.profiles (id, display_name, avatar_key)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data->>'display_name', split_part(NEW.email, '@', 1)),
    (ARRAY['goat','ibex','snow-leopard','eagle','wolf'])[floor(random()*5)::int + 1]
  )
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- ------------------------------------------------------------
-- 3) user_id on every data table: add → backfill to Shane →
--    NOT NULL + temporary DEFAULT (dropped in phase10).
-- ------------------------------------------------------------
DO $$
DECLARE
  shane uuid;
  t text;
BEGIN
  SELECT id INTO shane FROM auth.users WHERE email = 'shanehaynes.sah@gmail.com';
  IF shane IS NULL THEN
    RAISE EXCEPTION 'Create the shanehaynes.sah@gmail.com auth user before running phase9';
  END IF;

  INSERT INTO profiles (id, display_name, is_template_source)
  VALUES (shane, 'Shane', true)
  ON CONFLICT (id) DO UPDATE SET is_template_source = true;

  FOREACH t IN ARRAY ARRAY[
    'workout_events', 'recurring_exceptions', 'event_mutations_log',
    'workout_completions', 'workout_completion_log', 'workout_sessions',
    'workout_set_logs', 'workout_cardio_logs',
    'exercise_definitions', 'definition_mutations_log'
  ]
  LOOP
    EXECUTE format('ALTER TABLE %I ADD COLUMN IF NOT EXISTS user_id uuid REFERENCES auth.users (id) ON DELETE CASCADE', t);
    EXECUTE format('UPDATE %I SET user_id = %L WHERE user_id IS NULL', t, shane);
    EXECUTE format('ALTER TABLE %I ALTER COLUMN user_id SET NOT NULL', t);
    EXECUTE format('ALTER TABLE %I ALTER COLUMN user_id SET DEFAULT %L', t, shane);
  END LOOP;
END
$$;

-- ------------------------------------------------------------
-- 4) Per-user uniqueness. Upsert conflict targets in /api/* gain a
--    user_id prefix, so a forged event_id from user B can only ever
--    write into B's own partition — never clobber A's rows.
--    Old constraints are found dynamically (autogenerated names get
--    truncated by Postgres; never hardcode them).
-- ------------------------------------------------------------
DO $$
DECLARE cname text;
BEGIN
  -- workout_completions: PK event_id → (user_id, event_id)
  ALTER TABLE workout_completions DROP CONSTRAINT workout_completions_pkey;
  ALTER TABLE workout_completions ADD PRIMARY KEY (user_id, event_id);

  -- workout_sessions: UNIQUE (event_id, event_date) → (user_id, ...)
  SELECT conname INTO cname FROM pg_constraint
   WHERE conrelid = 'workout_sessions'::regclass AND contype = 'u';
  EXECUTE format('ALTER TABLE workout_sessions DROP CONSTRAINT %I', cname);
  ALTER TABLE workout_sessions ADD UNIQUE (user_id, event_id, event_date);

  -- workout_set_logs: UNIQUE (event_id, event_date, section, exercise_id, set_number)
  SELECT conname INTO cname FROM pg_constraint
   WHERE conrelid = 'workout_set_logs'::regclass AND contype = 'u';
  EXECUTE format('ALTER TABLE workout_set_logs DROP CONSTRAINT %I', cname);
  ALTER TABLE workout_set_logs ADD UNIQUE (user_id, event_id, event_date, section, exercise_id, set_number);

  -- workout_cardio_logs: UNIQUE (event_id, event_date, section, exercise_id)
  SELECT conname INTO cname FROM pg_constraint
   WHERE conrelid = 'workout_cardio_logs'::regclass AND contype = 'u';
  EXECUTE format('ALTER TABLE workout_cardio_logs DROP CONSTRAINT %I', cname);
  ALTER TABLE workout_cardio_logs ADD UNIQUE (user_id, event_id, event_date, section, exercise_id);

  -- exercise_definitions: the library is per-user, and ids are client-side
  -- slugs ('pistol-squat'), so a global PK would collide the moment a second
  -- user adds an exercise Shane already has. Composite PK also lets the
  -- template copy keep definition ids as-is (no JSONB definitionId remap).
  -- Nothing FK-references this table (set/cardio log definition_id is plain
  -- TEXT), so the swap is safe.
  SELECT conname INTO cname FROM pg_constraint
   WHERE conrelid = 'exercise_definitions'::regclass AND contype = 'u';
  EXECUTE format('ALTER TABLE exercise_definitions DROP CONSTRAINT %I', cname);
  ALTER TABLE exercise_definitions DROP CONSTRAINT exercise_definitions_pkey;
  ALTER TABLE exercise_definitions ADD PRIMARY KEY (user_id, id);
  ALTER TABLE exercise_definitions ADD UNIQUE (user_id, canonical_name);
END
$$;

-- ------------------------------------------------------------
-- 5) Indexes for per-user query patterns
-- ------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_we_user   ON workout_events (user_id, date);
CREATE INDEX IF NOT EXISTS idx_re_user   ON recurring_exceptions (user_id);
CREATE INDEX IF NOT EXISTS idx_ws_user   ON workout_sessions (user_id, event_date);
CREATE INDEX IF NOT EXISTS idx_wsl_user  ON workout_set_logs (user_id, event_date);
CREATE INDEX IF NOT EXISTS idx_wclg_user ON workout_cardio_logs (user_id, event_date);
CREATE INDEX IF NOT EXISTS idx_ed_user   ON exercise_definitions (user_id);

-- ------------------------------------------------------------
-- 6) Authenticated per-user SELECT policies on the 7 tables the client
--    reads directly. Added ALONGSIDE the anon read-all policies from
--    phase3/4/8 — those are dropped in phase10 once the authenticated
--    deploy is live. The 3 audit-log tables stay server-only (no policies).
--    Realtime postgres_changes delivery is authorized against these same
--    policies, so each user only receives their own row changes.
-- ------------------------------------------------------------
CREATE POLICY user_select_workout_events
  ON workout_events FOR SELECT TO authenticated
  USING (auth.uid() = user_id);

CREATE POLICY user_select_recurring_exceptions
  ON recurring_exceptions FOR SELECT TO authenticated
  USING (auth.uid() = user_id);

CREATE POLICY user_select_workout_completions
  ON workout_completions FOR SELECT TO authenticated
  USING (auth.uid() = user_id);

CREATE POLICY user_select_workout_sessions
  ON workout_sessions FOR SELECT TO authenticated
  USING (auth.uid() = user_id);

CREATE POLICY user_select_workout_set_logs
  ON workout_set_logs FOR SELECT TO authenticated
  USING (auth.uid() = user_id);

CREATE POLICY user_select_workout_cardio_logs
  ON workout_cardio_logs FOR SELECT TO authenticated
  USING (auth.uid() = user_id);

CREATE POLICY user_select_exercise_definitions
  ON exercise_definitions FOR SELECT TO authenticated
  USING (auth.uid() = user_id);
